tasks:
  installDeps:
    name: Install dependencies
    description: Install npm dependencies for the Nuxt app.
    command: |
      npm install
    triggeredBy:
      - postDevcontainerStart

services:
  dev-server:
    name: Dev Server
    description: Nuxt development server.
    commands:
      start: |
        npm run dev
      ready: |
        curl --silent --show-error --output /dev/null --write-out '%{http_code}' http://localhost:3000 | grep -qE '^[2345][0-9][0-9]$'
